### PR TITLE
Create sv_se.json

### PR DESCRIPTION
**Pull request by GeorgeOrwell1**
Added Swedish translations.

### CODE REVIEW

**Review by mdujovic17 — APPROVED** [review]

**Comment by GeorgeOrwell1** [comment]
Hey man could you just release an update with this translation so that I can play this mod with my friends in our native language?

**Comment by mdujovic17** [comment]
I thought to wait until Forge 1.17 was released to update this mod.
I'll try to release the mod in the next 24h, no promises though.

**Comment by mdujovic17** [comment]
Included in 1.1.2

**Comment by GeorgeOrwell1** [comment]
Thanks bro!

**Pull request merged**
